server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/digital_banking?currentSchema=auth_schema
    username: auth_user
    password: ${AUTH_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update   # KHÔNG dùng update/create trong production-style project, dùng Flyway, tạm thời sử dụng update trong quá trình phát triển
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  # Tạm thời tắt Redis - kích hoạt lại khi cần sử dụng
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

jwt:
  #private-key-path: classpath:keys/private_key.pem
  #public-key-path: classpath:keys/public_key.pem
  access-token-expiration: 900000      # 15 phút (ms)
  refresh-token-expiration: 604800000  # 7 ngày (ms)
